---
sidebar: sidebar
permalink: concept_tagging.html
keywords: tags, overview, conceptual, resource tags, volume tags
summary: Cloud Manager enables you to apply tags to your _existing_ resources to help organize and manage those resources. Tags are metadata that you can use to group resources to identify applications, environments, regions, billing codes, cloud providers, and more.
---

= Learn about tagging
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Manager enables you to apply tags to your _existing_ resources to help organize and manage those resources. Tags are metadata that you can use to group resources to identify applications, environments, regions, billing codes, cloud providers, and more.

Tags consists of a *tag key* and a *tag value*. For example, you can create a tag key called "Environment" and then tag values of "Production" and "Test". After they are applied to your resources, you can quickly search for and view resources that match the key/value pair.

You can add tag key/value pairs to _new_ resources when you create a new Azure NetApp Files volume. You can change or delete those tags using the tagging service, or add new tags.

== Features

The Tagging service offers the following features and benefits:

* Create tag keys and tag values that match the terms you use in your environment
* Organize the resources in your environment for easier monitoring and management
* Add, remove, and edit tag keys and tag values by resource type

== Pricing and licenses

The ability to tag your resources requires no licensing and is free to use by all Cloud Manager users.

== Resources that you can tag

You can apply tags to the following resources.

[cols=2*,options="header",cols="50,50",width="85%"]

|===
| Container
| Resource

| Cloud Volumes ONTAP | Storage VM
Aggregate
Volume

| On-premise ONTAP | Storage VM
Aggregate
Volume

| Azure NetApp Files | Volume

| AWS | EC2 Instance

|===

For information about AWS EC2 tags, refer to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html[AWS Documentation: Tagging your Amazon EC2 Resources^].

NOTE: At this time you can't view or manage tags assigned to resources though Azure, or labels assigned to resources though Google Cloud.

== Tag rules and restrictions

The following rules apply when creating tag keys and tag values:

* Maximum key length: 128 characters
* Maximum key value length: 256 characters
* Valid tag and tag value characters: letters, numbers, spaces, and special characters (_, @, &, *, etc.)
* Tags are case upper/lower sensitive.
* Maximum tags per resource: 30
* Per resource, each tag key must be unique

=== Tag examples

[cols=2*,options="header",cols="50,50",width="60%"]

|===
| Key
| Values

| Env | production
test

| Dept | finance
sales
eng

| Owner | admin
storage

|===
