---
sidebar: sidebar
permalink: concept_tagging.html
keywords: tags, overview, conceptual, resource tags, volume tags
summary: Cloud Manager enables you to apply tags to your _existing_ resources to help organize and manage those resources. Tags consists of a *tag key* and a *tag value*. For example, you can create a tag key called "Environment" and then tag values of "Production" and "Test". After they are applied to your resources, you can quickly sort and view only resources that match the key/value pair.
---

= Learn about tagging
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Manager enables you to apply tags to your _existing_ resources to help organize and manage those resources. Tags consists of a *tag key* and a *tag value*. For example, you can create a tag key called "Environment" and then tag values of "Production" and "Test". After they are applied to your resources, you can quickly sort and view only resources that match the key/value pair.

You can add tag key/value pairs to _new_ resources when you create a Cloud Volumes ONTAP working environment or when you create a new Azure NetApp Files volume. You can change or delete those tags using the tagging service, or add new tags.

== Features

The Tagging service offers the following features and benefits:

* Create tag keys and tag values that match the terms you use in your environment
* Organize the resources in your environment for easier monitoring and management
* Add, remove, and change tag and tag values as necessary

== Pricing and licenses

The ability to tag your resources requires no licensing and is free to use by all Cloud Manager users.

== Resources that you can tag

At this time you can apply tags to the following resources.

[cols=2*,options="header",cols="50,50"]

|===
| Container
| Resource

| Cloud Volumes ONTAP | Storage VM
Aggregate
Volume

| On-premise ONTAP | Storage VM
Aggregate
Volume

| Azure NetApp Files | Volume

|===

== Tag rules and restrictions

The following rules apply when creating tag keys and tag values:

* 
