---
sidebar: sidebar
permalink: reference_google_support.html
keywords: google, gcp, regions, google regions, gcp regions, storage class, standard, nearline, coldline, archive
summary: Cloud Tiering supports several Google Cloud storage classes and most regions.
---

= Supported Google Cloud storage classes and regions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Tiering supports several Google Cloud storage classes and most regions.

== Supported storage classes

Cloud Tiering can apply a lifecycle rule so the data transitions from the _Standard_ storage class to another storage class after 30 days. You can choose from the following storage classes:

* Nearline
* Coldline
* Archive

If you choose Standard, then the data remains in that storage class and no rules are applied.

link:https://cloud.google.com/storage/docs/storage-classes[Learn about Google Cloud Storage classes^].

== Supported Google Cloud regions

Cloud Tiering supports the following regions.

=== Americas

* Iowa
* Los Angeles
* Montreal
* N. Virginia
* Oregon
* Sao-Paulo
* South Carolina

=== Asia Pacific

* Hong Kong
* Mumbai
* Osaka
* Singapore
* Sydney
* Taiwan
* Tokyo

=== Europe

* Belgium
* Finland
* Frankfurt
* London
* Netherlands
* Zurich
