---
sidebar: sidebar
permalink: reference_issues.html
keywords: issues, bugs, known issues
summary: Known issues identify problems that might prevent you from using this release of the product successfully.
---

= Known issues
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known issues identify problems that might prevent you from using this release of the product successfully.

You can find known issues for Cloud Volumes ONTAP in the https://docs.netapp.com/us-en/cloud-volumes-ontap/[Cloud Volumes ONTAP Release Notes^] and for ONTAP software in general in the https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP Release Notes^].

== Possible conflict with IP addresses in the 172 range

Cloud Manager deploys the Connector with two interfaces that have IP addresses in the 172.17.0.0/16 and 172.18.0.0/16 ranges.

If your network has a subnet configured with either of these ranges, then you might experience connectivity failures from Cloud Manager. For example, discovering on-prem ONTAP clusters in Cloud Manager might fail.

The workaround is to change the IP addresses of the Connector's interfaces. Contact NetApp Support for help.
