---
sidebar: sidebar
permalink: task_adding_nss_accounts.html
keywords: adding, creating, netapp support site account, nss
summary: Adding your NetApp Support Site account to Cloud Manager is required to deploy a node-based BYOL system. It's also required to register pay-as-you-go systems and to upgrade ONTAP software.
---

= Adding NetApp Support Site accounts to Cloud Manager
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Adding your NetApp Support Site account to Cloud Manager is required to deploy a node-based BYOL system or to enter the serial number for a capacity-based license. It's also required to register pay-as-you-go systems and to upgrade ONTAP software.

.Steps

. If you don't have a NetApp Support Site account yet, https://register.netapp.com/register/start[register for one^].

. In the upper right of the Cloud Manager console, click the Help icon, and select *Support*.

. Click *NSS Management > Add NSS Account*.

. Enter the user name and password for your account.
+
* The account must be a customer-level account (not a guest or temp account).
* If you plan to deploy a node-based BYOL system:
** The account must be authorized to access the serial numbers of the BYOL systems.
** If you purchased a secure BYOL subscription, then a secure NSS account is required.

. Click *Register*.

.What's next?

Users can now select the account when creating new Cloud Volumes ONTAP systems and when registering existing systems.

* link:task_deploying_otc_aws.html[Launching Cloud Volumes ONTAP in AWS]
* link:task_deploying_otc_azure.html[Launching Cloud Volumes ONTAP in Azure]
* link:task_registering.html[Registering pay-as-you-go systems]
* link:concept_licensing.html[Learn how Cloud Manager manages license files]
