---
sidebar: sidebar
permalink: task_managing_svms_azure.html
keywords: storage virtual machine, vserver, svm, storage vm, supported number, number supported
summary: A storage VM is a virtual machine running within ONTAP that provides storage and data services to your clients. You might know this as an SVM or a vserver. Cloud Volumes ONTAP is configured with one storage VM by default, but some configurations support additional storage VMs.
---

= Create data-serving storage VMs for Cloud Volumes ONTAP in Azure
:toc: macro
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
A storage VM is a virtual machine running within ONTAP that provides storage and data services to your clients. You might know this as an _SVM_ or a _vserver_. Cloud Volumes ONTAP is configured with one storage VM by default, but additional storage VMs are supported when running Cloud Volumes ONTAP in Azure.

To create additional data-serving storage VMs, you need to allocate IP addresses in Azure, set up the load balancer for an HA pair, and then run ONTAP commands to create the storage VM and data LIFs.

== Supported number of storage VMs

Multiple storage VMs are supported with Cloud Volumes ONTAP BYOL in Azure with an add-on license starting with the 9.9.0 release. Go to the https://docs.netapp.com/us-en/cloud-volumes-ontap/index.html[Cloud Volumes ONTAP Release Notes^] to verify the supported number of storage VMs for your version of Cloud Volumes ONTAP.

All other Cloud Volumes ONTAP configurations support one data-serving storage VM and one destination storage VM used for disaster recovery. You can activate the destination storage VM for data access if there's an outage on the source storage VM.

== Allocate IP addresses in Azure

IP addresses must be assigned to nic0 in Azure before you create the storage VM and allocate LIFs.

You'll need to create an IP address for data LIF access from node 1, another IP address for data LIF access from node 2 (HA pairs only), and another optional IP address for a storage VM (SVM) management LIF. This management LIF provides a connection to management tools like SnapCenter.

.Steps

. Log in to the Azure portal and open the Virtual machine service.

. Click the name of the Cloud Volumes ONTAP VM.

. Click *Networking*.

. Click the name of the network interface for nic0.

. Click *IP configurations*.

. Click *Add*.

. Enter a name for the IP configuration, select *Static*, and then click *OK*.

. Repeat the last two steps for any additional IP addresses that you need.

== Modify the load balancer for an HA pair

If you have an HA pair, you need to modify the load balancer so that the IP addresses can migrate to the other node when failover events occur.

.Steps

. In the Azure portal, go to the Load balancers service.

. Click the name of the load balancer for the HA pair.

. Create one frontend IP configuration for data LIF access from node 1, another for data LIF access from node 2 (HA pairs only), and another optional frontend IP for a storage VM (SVM) management LIF.

.. Click *Frontend IP configuration*.

.. Click *Add*.

.. Enter a name for the frontend IP, select the default subnet, and leave *Dynamic* selected.

. Add a health probe for each frontend IP that you just created.

.. Under the load balancer's *Settings*, click *Health probes*.

.. Click *Add*.

.. Enter a name for the health probe and enter a port number that's between 63005 and 63500. Keep the default values for the other fields.
+
It's important that the port number is between 63005 and 63500. For example, if you are creating three health probes, you could enter probes that use port numbers 63005, 63006, and 63007.

. Create new load balancing rules for each frontend IP.

.. Under the load balancer's *Settings*, click *Load balancing rules*.

.. Click *Add*.

.. Enter a name, select the frontend IP address, select the health probe that you created, set session persistence to None, idle timeout to 30 minutes, and enable floating IP.

== Create a storage VM

These steps create a new storage VM on a single node system or an HA pair. One IP address is required to create a NAS LIF on a node (two total for an HA pair) and another optional IP address is needed if you want to create a management LIF.

.Steps

. Create the storage VM and a route to the storage VM.
+
[source,cli]
vserver create -vserver svm_2 -subtype default -rootvolume root_svm_2 -rootvolume-security-style mixed -snapshot-policy default
+
[source,cli]
network route create -destination 0.0.0.0/0 -vserver svm_2 -gateway subnet_gateway

. Create a NAS LIF on node 1.
+
[source,cli]
net int create -vserver svm_2 -lif data_1 -role data -data-protocol cifs,nfs,fcache -address 99.0.99.22 -netmask-length 24 -home-node MultiSVMforHA-01 -status-admin up -failover-policy system-defined -firewall-policy data -home-port e0a -auto-revert true -failover-group Default -probe-port 63006

. Create a NAS LIF on node 2 (for HA pairs only).
+
[source,cli]
net int create -vserver svm_2 -lif data_2 -role data -data-protocol cifs,nfs,fcache -address 99.0.99.23 -netmask-length 24 -home-node MultiSVMforHA-02 -status-admin up -failover-policy system-defined -firewall-policy data -home-port e0a -auto-revert true -failover-group Default -probe-port 63007

. Optional: Create a storage VM management LIF on node 1.
+
[source,cli]
net int create -vserver svm-name -lif lif-name -role data -data-protocol cifs,nfs,fcache -address ip-address -netmask-length 24 -home-node node1 -status-admin up -failover-policy system-defined -firewall-policy data -home-port e0a -auto-revert true -failover-group Default -probe-port port-number
