---
sidebar: sidebar
permalink: task_setting_up_permissions_fsx.html
keywords: fsx for ontap, iam, user role, permissions
summary: In order to create or manage your Amazon FSx for ONTAP working environment, you need to have an AWS access key and secret key for an IAM user role with FSx for ONTAP permissions.
---

= Setting up permissions for FSx for ONTAP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To create or manage your Amazon FSx for ONTAP working environment, you need an AWS access key and secret key for an IAM user role with FSx for ONTAP permissions. These permissions are different from the permissions required to create a Connector in AWS.

NOTE: You can create a new IAM user role with FSx for ONTAP permissions or edit an existing IAM user role to include the additional FSx for ONTAP permissions to avoid having to use multiple keys for Connectors and FSx for ONTAP.

.Steps

To create a new Connector for AWS that includes required permissions for FSx for ONTAP:

. From the AWS IAM console, create a new policy or edit an existing policy to include the following actions for FSx for ONTAP:
+
[source,json]
"ec2:Describe*"
"kms:Describe*"
"kms:List*"
"fsx:*"
"iam:CreateServiceLinkedRole"
"ec2:CreateTags"
+
https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_create.html[AWS Documentation: Creating IAM Policies^]

. Attach the policy that you created in the previous step to the IAM user who will create the Connector from Cloud Manager.
+
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create.html[AWS Documentation: Creating IAM Roles^]
+
https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html[AWS Documentation: Adding and Removing IAM Policies^]

.Result

The AWS user now has the permissions required for FSx for ONTAP in Cloud Manager.

== Related links

link:task_creating_connectors_aws[Create a Connecter in AWS]
link:task_adding_aws_accounts[Managing AWS credentials for Cloud Manager]
